--CREATE TABLE song_source (Artist TEXT NOT NULL, Albums TEXT NOT NULL, Song_name TEXT NOT NULL, youtube_link TEXT NOT NULL, image_loc TEXT NOT NULL);
INSERT INTO song_source (Artist, Albums, Song_name, youtube_link, image_loc)
VALUES 
-- ("Baby Monster", "Drip", "Click Clack", "o0oW3lPoOXMB", "babymonster_drip"),
-- ("Baby Monster", "Drip", "Drip", "Zp-Jhuhq0bQ", "babymonster_drip"),
-- ("Baby Monster", "Drip", "Love Maybe", "_MlIlA1RJwg", "babymonster_drip"),
-- ("Baby Monster", "Drip", "Really Like You", "eCFlXhPmaBs", "babymonster_drip"),
-- ("Baby Monster", "Drip", "BILLIONARE", "kBLEW6gXhGE", "babymonster_drip"),
-- ("Baby Monster", "Drip", "Love In My Heart", "1kXLsrun51s", "babymonster_drip"),
-- ("Baby Monster", "Drip", "Woke Up In Tokyo", "KcSwEoDRWTA", "babymonster_drip"),
-- ("Baby Monster", "Drip", "Forever", "eJCHKjt0MPw", "babymonster_drip"),
-- ("Baby Monster", "Drip", "Batter UP (Remix)", "YBdJSP2fLxc", "babymonster_drip"),
-- ("WayV", "Frequency", "Frequency (Kor Version)", "XHW2P48kqAE", "babymonster_drip"),
-- ("WayV", "Frequency", "High Five", "rA0R10bZOnw", "wayv_frequency"),
-- ("WayV", "Frequency", "Twist", "SqOwJYqbbH4", "wayv_frequency"),
-- ("WayV", "Frequency", "Filthy Rich", "0m7psXvzM9c", "wayv_frequency"),
-- ("WayV", "Frequency", "Call Me", "RDgPJYe93gk", "wayv_frequency"),
-- ("WayV", "Frequency", "Frequency (CHN Version)", "Fd-6UPZEhhI", "wayv_frequency");
-- ("Seventeen", "Spill The Feels", "Eyes On You", "JjvX09nG2F0", "svt_spill_feels"),
-- ("Seventeen", "Spill The Feels", "1 TO 13","Cx4ytbd2tZI", "svt_spill_feels"),
-- ("Seventeen", "Spill The Feels", "Love Money Fame", "5NPe8_gDSr4", "svt_spill_feels"),
-- ("Seventeen", "Spill The Feels", "Rain", "r2wizo1mz-w", "svt_spill_feels"),
-- ("Seventeen", "Spill The Feels", "Candy", "tA-FizlZp7Q", "svt_spill_feels"),
-- ("Seventeen", "Spill The Feels", "Water", "bGgeM2VxMzM", "svt_spill_feels")
-- ("TWS", "Last Bell", "Highlight", "RvBrWryLnEE", "tws_lastbell"),
-- ("TWS", "Last Bell", "Last Festival", "-XHCYeCGlgw", "tws_lastbell"),
-- ("TWS", "Last Bell", "Comma", "ptlWIjtQ9UY", "tws_lastbell"),
-- ("NEXZ", "Nallina", "Hard", "2ThCMSt1E6s", "nexz_nallina"),
-- ("NEXZ", "Nallina", "Nallina", "WlsTyEGK9I8", "nexz_nallina"),
-- ("NEXZ", "Nallina", "Next Zeneration", "qGtw2Ki1kd8", "nexz_nallina"),
-- ("NEXZ", "Nallina", "Keep on Moving (Kor Version)", "DLKgKmc0Qlk", "nexz_nallina"),
-- ("NEXZ", "Nallina", "Eye to Eye", "V98t1arsFvA", "nexz_nallina");
-- ("Jin", "Happy", "Running Wild", "", "jin_Happy"),
-- ("Jin", "Happy", "I'll Be There", "0HBBJKzdn30", "jin_Happy"),
-- ("Jin", "Happy", "Another Level", "PIYkh9v4L6I", "jin_Happy"),
-- ("Jin", "Happy", "Falling", "RDtjsZx_d40", "jin_Happy"),
-- ("Jin", "Happy", "Heart on the Window ft Wendy", "KlAxdVCDzUU", "jin_Happy"),
-- ("Jin", "Happy", "I Will Come To You", "bFqRFkRy_dQ", "jin_Happy"),
-- ("Illit", "I'll Like You", "I'll Like You", "NChlBP5DSc4", "illit_likeyou"),
-- ("Illit", "I'll Like You", "Cherish(My love)", "tbDGl7jEazA", "illit_likeyou"),
-- ("Illit", "I'll Like You", "IYKYK (If You Know You Know)", "qh7F1sFkOaY", "illit_likeyou"),
-- ("Illit", "I'll Like You", "Pimple", "4ehnJaIcEAI", "illit_likeyou"),
-- ("Illit", "I'll Like You", "Tick Tack", "-nEGVrzPaiU", "illit_likeyou");
-- ("Stray Kids", "Giant", "Giant", "43RdbR4ixa8", "skz_giant"),
-- ("Stray Kids", "Giant", "Chk Chk Boom (Jap Version)", "f6Gu5kmP7KM", "skz_giant"),
-- ("Stray Kids", "Giant", "Night", "xhHE8pYt74g", "skz_giant"),
-- ("Stray Kids", "Giant", "Falling Up", "HF7cDT9LFsE", "skz_giant"),
-- ("Stray Kids", "Giant", "WHY?", "0SP8ie--amY", "skz_giant"),
-- ("Stray Kids", "Giant", "Saiyan", "Q4vEPBlcPGo", "skz_giant"),
-- ("Stray Kids", "Giant", "Aiwokuretanoninaze", "BLfrPSSO_YI", "skz_giant"),
-- ("Stray Kids", "Giant", "Christmas Love", "2EH0EZdrYo4", "skz_giant"),
-- ("Stray Kids", "Giant", "Night (Eng Version)", "78Nm5oc-O5M", "skz_giant"),
-- ("Stray Kids", "Giant", "Falling (Eng Version)", "ULYpLm7q4nQ", "skz_giant"),
-- ("NCT Dream", "Dreamscape", "INTRO: DREAMSCAPE", "wShvjbdiTzg", "dreamies_dreamscape"),
-- ("NCT Dream", "Dreamscape", "When I&#39m With You", "B1qq8IvzSz4", "dreamies_dreamscape"),
-- ("NCT Dream", "Dreamscape", "Flying Kiss", "oFRnSLNtSbc", "dreamies_dreamscape"),
-- ("NCT Dream", "Dreamscape", "I hate Fruits", "OsKOz9e2ZlY", "dreamies_dreamscape"),
-- ("NCT Dream", "Dreamscape", "No Escape", "6on-5rJyVOo", "dreamies_dreamscape"),
-- ("NCT Dream", "Dreamscape", "Best Of Me", "NuH3baf37Pc", "dreamies_dreamscape"),
-- ("NCT Dream", "Dreamscape", "YOU", "9i64Oh5auU0", "dreamies_dreamscape"),
-- ("NCT Dream", "Dreamscape", "Heavenly", "L0VLpZS3pQc", "dreamies_dreamscape"),
-- ("NCT Dream", "Dreamscape", "Night Poem", "NEYNwYfzVuQ", "dreamies_dreamscape"),
-- ("NCT Dream", "Dreamscape", "Off the Wall", "UGLSBo7wlmM", "dreamies_dreamscape"),
-- ("NCT Dream", "Dreamscape", "Rains In Heaven", "6s1YRHgytwA", "dreamies_dreamscape"),
("Minho", "Callback", "Callback", "1TbJHo7BM44", "minho_callback"),
("Minho", "Callback", "Slow Down", "MNEVs-WjUE8", "minho_callback"),
("Minho", "Callback", "FIREWORKS", "90AT9ZEow3c", "minho_callback"),
("Minho", "Callback", "Came And Left Me", "C3RTTYqt89k", "minho_callback"),
("Minho", "Callback", "Something About U", "gJEBbZQEKWE", "minho_callback"),
("Minho", "Callback", "Round Kick", "bdFykg9kw58", "minho_callback"),
("Minho", "Callback", "Affection", "zMlFVqQ1NJo", "minho_callback"),
("Minho", "Callback", "I Don't Miss You", "9JTQ7FnyENY", "minho_callback"),
("Minho", "Callback", "Because Of You", "LlMOMShCCBY", "minho_callback"),
("Minho", "Callback", "Would You Mind", "bfL55ntadw4", "minho_callback");


